"""add test cycle test case mapping

Revision ID: 088442c27755
Revises: 9b6858a7dbf7
Create Date: 2026-09-24 15:35:12.757830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088442c27755'
down_revision: Union[str, Sequence[str], None] = '9b6858a7dbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cycles_project_id'), 'test_cycles', ['project_id'], unique=False)
    op.create_table('test_cycle_test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_cycle_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_cycle_id'], ['test_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_cycle_id', 'test_case_id', name='uq_test_cycle_test_case')
    )
    op.create_index(op.f('ix_test_cycle_test_cases_test_case_id'), 'test_cycle_test_cases', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_test_cycle_test_cases_test_cycle_id'), 'test_cycle_test_cases', ['test_cycle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_cycle_test_cases_test_cycle_id'), table_name='test_cycle_test_cases')
    op.drop_index(op.f('ix_test_cycle_test_cases_test_case_id'), table_name='test_cycle_test_cases')
    op.drop_table('test_cycle_test_cases')
    op.drop_index(op.f('ix_test_cycles_project_id'), table_name='test_cycles')
    op.drop_table('test_cycles')
    # ### end Alembic commands ###
