"""add test steps

Revision ID: 8d3f6f66a672
Revises: e8632e650f75
Create Date: 2026-09-24 12:38:28.000532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d3f6f66a672'
down_revision: Union[str, Sequence[str], None] = 'e8632e650f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_steps_test_case_id'), 'test_steps', ['test_case_id'], unique=False)
    op.drop_constraint(op.f('uq_tags_name'), 'tags', type_='unique')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.drop_column('test_cases', 'steps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_unique_constraint(op.f('uq_tags_name'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_test_steps_test_case_id'), table_name='test_steps')
    op.drop_table('test_steps')
    # ### end Alembic commands ###
