"""add  module,test-step execution

Revision ID: ac5065adbe2a
Revises: c0ddcdcfaf25
Create Date: 2026-09-28 17:09:24.611098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5065adbe2a'
down_revision: Union[str, Sequence[str], None] = 'c0ddcdcfaf25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
