"""add  module,test-step execution

Revision ID: c0ddcdcfaf25
Revises: 088442c27755
Create Date: 2026-09-28 17:07:25.696016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ddcdcfaf25'
down_revision: Union[str, Sequence[str], None] = '088442c27755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_modules_project_id'), 'test_modules', ['project_id'], unique=False)
    op.create_table('test_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_cycle_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_cycle_id'], ['test_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_executions_test_case_id'), 'test_executions', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_test_executions_test_cycle_id'), 'test_executions', ['test_cycle_id'], unique=False)
    op.create_table('test_step_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_execution_id', sa.UUID(), nullable=False),
    sa.Column('test_step_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_execution_id'], ['test_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_step_id'], ['test_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_execution_id', 'test_step_id', name='uq_test_step_execution')
    )
    op.create_index(op.f('ix_test_step_executions_test_execution_id'), 'test_step_executions', ['test_execution_id'], unique=False)
    op.create_index(op.f('ix_test_step_executions_test_step_id'), 'test_step_executions', ['test_step_id'], unique=False)
    op.add_column('test_cases', sa.Column('module_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_test_cases_module_id'), 'test_cases', ['module_id'], unique=False)
    op.create_foreign_key(None, 'test_cases', 'test_modules', ['module_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.drop_index(op.f('ix_test_cases_module_id'), table_name='test_cases')
    op.drop_column('test_cases', 'module_id')
    op.drop_index(op.f('ix_test_step_executions_test_step_id'), table_name='test_step_executions')
    op.drop_index(op.f('ix_test_step_executions_test_execution_id'), table_name='test_step_executions')
    op.drop_table('test_step_executions')
    op.drop_index(op.f('ix_test_executions_test_cycle_id'), table_name='test_executions')
    op.drop_index(op.f('ix_test_executions_test_case_id'), table_name='test_executions')
    op.drop_table('test_executions')
    op.drop_index(op.f('ix_test_modules_project_id'), table_name='test_modules')
    op.drop_table('test_modules')
    # ### end Alembic commands ###
